### ISSUE TITLE
Detect canUseDOM and prevent "Invariant Violation: React DOM tree root should always have a node reference." in server rendering?

### ISSUE THREAD

**Issue by ericfong** [nkbt/react-interval#8]
Just want to report, when using in react-interval server rendering.

And wrongly enabled the interval will make react output 
"Invariant Violation: React DOM tree root should always have a node reference." in server rendering
and the server will be crashed

I think better to have a warning or complete disable all interval when we detect
```
import {canUseDOM} from 'fbjs/lib/ExecutionEnvironment'
```

Thanks

**Comment by nkbt** [comment]
It should not have any problems with server-side rendering since it does not use `ReactDOM`. It is purely React/vanilla-js library.

Can you give some more context please? Would be nice to figure out why that might happen for you.

Thanks, @ericfong!

**Comment by ericfong** [comment]
because we use ReactInterval to trigger state change
```
      <ReactInterval
        timeout={60 * 1000}
        enabled={true}
        callback={() => this.setState({date: Date.now()})} />
```

And in server side, the dom is rendered and gone when the interval callback is called.

Of cause, we should have some checking in our callback. But I think it is very common to trigger state change in ReactInterval callback. So I think we better warn them or stop it in server.

Thanks

**Comment by nkbt** [comment]
Hm interesting. Never experienced that. I don't really want to warn about it, would be better to actually work properly on the server side instead.

**Comment by nkbt** [comment]
Ha! gotcha.

https://github.com/nkbt/react-interval/blob/master/src/ReactInterval.js#L63-L70

Timer is started on render, should be in `componentWillReceiveProps` and `componentDidMount` instead, since those lifecycle methods are not run on server!

**Comment by ericfong** [comment]
If you change state in server rendering (after the dom is renderred) you will get:
```
Invariant Violation: React DOM tree root should always have a node reference.
    at invariant (/Users/eric/workspace/ec5/src/node_modules/fbjs/lib/invariant.js:38:15)
    at getNodeFromInstance (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactDOMComponentTree.js:166:65)
    at ReactDOMComponent.Mixin.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactDOMComponent.js:943:12)
    at Object.ReactReconciler.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:67:29)
    at ReactCompositeComponentMixin.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:371:28)
    at Object.ReactReconciler.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:67:29)
    at ReactCompositeComponentMixin.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:371:28)
    at Object.ReactReconciler.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:67:29)
    at ReactCompositeComponentMixin.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:371:28)
    at Object.ReactReconciler.getHostNode (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:67:29)
    at ReactDOMComponent.ReactMultiChild.Mixin._updateChildren (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactMultiChild.js:341:42)
    at ReactDOMComponent.ReactMultiChild.Mixin.updateChildren (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactMultiChild.js:298:12)
    at ReactDOMComponent.Mixin._updateDOMChildren (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactDOMComponent.js:938:12)
    at ReactDOMComponent.Mixin.updateComponent (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactDOMComponent.js:767:10)
    at ReactDOMComponent.Mixin.receiveComponent (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactDOMComponent.js:723:10)
    at Object.ReactReconciler.receiveComponent (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:131:22)
    at ReactCompositeComponentMixin._updateRenderedComponent (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:729:23)
    at ReactCompositeComponentMixin._performComponentUpdate (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:707:10)
    at ReactCompositeComponentMixin.updateComponent (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:626:12)
    at ReactCompositeComponentMixin.performUpdateIfNecessary (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactCompositeComponent.js:540:12)
    at Object.ReactReconciler.performUpdateIfNecessary (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactReconciler.js:165:22)
    at runBatchedUpdates (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactUpdates.js:152:21)
    at ReactReconcileTransaction.Mixin.perform (/Users/eric/workspace/ec5/src/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction.Mixin.perform (/Users/eric/workspace/ec5/src/node_modules/react/lib/Transaction.js:138:20)
    at ReactUpdatesFlushTransaction._assign.perform (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactUpdates.js:91:38)
    at Object.flushBatchedUpdates (/Users/eric/workspace/ec5/src/node_modules/react/lib/ReactUpdates.js:178:19)
    at ReactDefaultBatchingStrategyTransaction.Mixin.closeAll (/Users/eric/workspace/ec5/src/node_modules/react/lib/Transaction.js:204:25)
    at ReactDefaultBatchingStrategyTransaction.Mixin.perform (/Users/eric/workspace/ec5/src/node_modules/react/lib/Transaction.js:151:16)
```

**Comment by nkbt** [comment]
I understand that and know how to actually fix the problem.

**Comment by ericfong** [comment]
thanks

**Comment by nkbt** [comment]
Publised + react-interval@1.3.2

**Comment by nkbt** [comment]
Let me know if you still have this issue and feel free to reopen!
